server:
  port: 8888

spring:
  application:
    name: Gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8030"
            allowedHeaders:
              - "Origin"
              - "Content-Type"
              - "Accept"
              - "Authorization"
              - "Referer"
            allowedMethods:
              - POST
              - GET
              - OPTIONS
      routes:
        - id: user-ms-route
          uri: http://localhost:8030
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/user/(?<remaining>.*), /$\{remaining}
        - id: recette-ms-route
          uri: http://localhost:8091
          predicates:
            - Path=/api/recette/**
          filters:
            - RewritePath=/recette/v1/(?<remaining>.*), /$\{remaining}

eureka:
  instance:
    hostname: localhost


