spring:
  application:
    name: RECETTE-MS
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery: RECETTE-MS
      config:
        enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/recette-ms
    username: root
    password: P@$$w0rd
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8091
userUrl: http://localhost:8030/api/user